[package]
name = "homomorphic_game_of_life_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = { version = "0.2.0-beta", features = ["booleans", "serde"]}
rayon = "1.5.3"
bincode = "1.3.3"


[profile.release]
lto = "fat"